### ISSUE TITLE
Should I take this class?

### ISSUE THREAD

**Issue by acestronautical** [bhanderson/cpts471#3]
Debating between this and CPTS451 (databases), did you feel this was a valuable course?

**Comment by bhanderson** [comment]
Computational genomics was really rewarding with Ananth. Databases would probably be more practical but genomics was a really fun class and I got to work on a really cool algorithm project. So I guess it’s more of what type of class are you looking for. Both will teach you quite a bit I’m sure.

**Comment by acestronautical** [comment]
Thanks Bryce! I think I'll go ahead and take it (ananth is still the instructor). Closing this issue ;)
